name: Update Zip Data

on:
  schedule:
    - cron: '0 0 1,15 * *'  # 毎月1日と15日のUTC 0:00に実行します。
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun run src/index.ts

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.email "wada@coffee-break-designs.com"
          git config --global user.name "ZipCodeJSON-JP Bot"
          git checkout -b "auto-update/${{ github.run_id }}"
          git add -A
          if git diff --staged --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
            echo "No changes to commit, exiting gracefully."
            exit 0  # 明示的に成功の終了コードで終了させる
          else
            echo "changes=true" >> $GITHUB_ENV
            git commit -m "Update zip data"
            git push --set-upstream origin "auto-update/${{ github.run_id }}"

      - name: Create Pull Request
        if: env.changes == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update zip data"
          title: "Data Update"
          body: "This is an automated PR to update data."
          branch: "auto-update/${{ github.run_id }}"
          base: "master"

      - name: Notify
        if: env.changes == 'true'
        run: echo "Changes have been pushed and a PR has been created."
